# action.yml
name: "Create screenshots"
description: "Creeate screenshots for the app"
inputs:
  flutter-version:
    description: "Version of Flutter to use"
    required: true
  java-version:
    description: "Version of Java to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "adopt"

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: |
          /opt/hostedtoolcache/flutter
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Create screenshots
      shell: bash
      run: dart test_driver/emulator_runner.dart

    - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
            name: screenshots
            path: screenshots
