# action.yml
name: "Upload to TestFlight"
description: "Upload a new build to TestFlight"
inputs:
  flutter-version:
    description: "Version of Flutter to use"
    required: true
  java-version:
    description: "Version of Java to use"
    required: true
  apple_application_specific_password:
    description: "Apple Application Specific Password"
    required: true
  app_store_connect_key_content:
    description: "App Store Connect Key Content"
    required: true
  app_store_connect_issuer_id:
    description: "App Store Connect Issuer ID"
    required: true
  match_password:
    description: "Match Password"
    required: true
  match_git_basic_authorization:
    description: "Match Git Basic Authorization"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: |
          /opt/hostedtoolcache/flutter
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
        bundler-cache: true
        working-directory: "ios"

    - name: Install Pods
      shell: bash
      run: pod install
      working-directory: "ios"

    - name: Deploy to TestFlight
      uses: maierj/fastlane-action@v3.0.0
      with:
        lane: "beta"
        subdirectory: "ios"
        verbose: true
      env:
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ inputs.apple_application_specific_password }}
        APP_STORE_CONNECT_KEY_CONTENT: ${{ inputs.app_store_connect_key_content }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ inputs.app_store_connect_issuer_id }}
        APP_STORE_CONNECT_KEY_ID: "UTV2V4K6M7"
        MATCH_PASSWORD: ${{ inputs.match_password }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ inputs.match_git_basic_authorization }}
