# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :take_screenshots do
  Dir.chdir('../..') do
    sh('dart', './test_driver/emulator_runner.dart')
  end
end

desc 'Description of what the lane does'
lane :custom_lane do
  # add actions here: https://docs.fastlane.tools/actions
end

lane :framescreenshots do
  Dir.chdir('../..') do
    frameit(path: File.expand_path('./screenshots/store/ios'))
  end
end

lane :beta do
  setup_ci

  sh('flutter', 'build', 'ios', '--release', '--no-codesign')

  match(type: 'appstore')

  build_app(
    skip_build_archive: true,
    archive_path: '../build/ios/archive/Runner.xcarchive'
  )

  upload_to_testflight(submit_beta_review: false, skip_submission: true, skip_waiting_for_build_processing: true)
end
