# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


lane :take_screenshots do
  Dir.chdir("../..") do
    sh("dart", "./test_driver/emulator_runner.dart")
  end
end

desc "Description of what the lane does"
lane :custom_lane do
  # add actions here: https://docs.fastlane.tools/actions
end

lane :framescreenshots do
  Dir.chdir("../..") do
    frameit(path: File.expand_path("./screenshots/store/ios"))
  end
end

lane :beta do
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
    duration: 1200,
    in_house: false
  )
  match(type: "appstore")
  # Get the latest build number from TestFlight
  previous_build_number = latest_testflight_build_number(
  app_identifier: 'com.trost.scorecard',
  api_key: api_key,
  )

  # Increment the build number by 1
  current_build_number = previous_build_number + 1
  increment_build_number(
    build_number: current_build_number
  )

  # build_app(scheme: "Runner")
  gym(export_method: "app-store", scheme: "Runner")
  upload_to_testflight(submit_beta_review: false, skip_submission: true, skip_waiting_for_build_processing: true)
end
