# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


lane :take_screenshots do
  sh("dart", "../../test_driver/emulator_runner.dart")
end

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :framescreenshots do
    frameit(path: File.expand_path("../../screenshots/ios"))
  end
end

platform :android do
  lane :framescreenshots do
    frameit(path: File.expand_path("../../screenshots/android"))
  end
end
