name: Continuous integration

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.10.6
  JAVA_VERSION: 11

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create screenshots
        uses: ./.github/workflows/screenshot-generation-action
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
